apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
  labels:
    app: otel-collector
  annotations:
    reload.linkerd.io/auto: "true"
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          http:
          grpc:
    processors:
      batch:
      memory_limiter:
        limit_mib: 512
        spike_limit_mib: 128
        check_interval: 5s
    exporters:
      logging:
        loglevel: warn
      otlp/datadog:
        endpoint: https://api.datadoghq.com
        headers:
          DD-API-KEY: ${DATADOG_API_KEY}
      otlphttp/tempo:
        endpoint: https://tempo.observability.svc.cluster.local:4318
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/datadog, otlphttp/tempo]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/datadog]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app: otel-collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
        linkerd.io/inject: enabled
    spec:
      serviceAccountName: otel-collector
      containers:
        - name: collector
          image: otel/opentelemetry-collector:0.104.0
          args: ["--config=/conf/collector.yaml"]
          env:
            - name: DATADOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datadog-api
                  key: key
          volumeMounts:
            - name: config
              mountPath: /conf
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observability
spec:
  selector:
    app: otel-collector
  ports:
    - name: grpc
      port: 4317
    - name: http
      port: 4318
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: observability
