apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: platform-gateway
  namespace: platform
spec:
  replicas: 4
  strategy:
    canary:
      canaryService: platform-gateway-canary
      stableService: platform-gateway
      steps:
        - setWeight: 25
        - pause: { duration: 120 }
        - setWeight: 50
        - pause: { duration: 120 }
        - setWeight: 100
      trafficRouting:
        alb:
          ingress: platform-gateway
          servicePort: 80
  selector:
    matchLabels:
      app: platform-gateway
  template:
    metadata:
      labels:
        app: platform-gateway
    spec:
      containers:
        - name: graphql-router
          image: ghcr.io/tribalmingle/platform-gateway:latest
          ports:
            - containerPort: 8080
