name: platform-gateway

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
    secrets:
      GHCR_TOKEN:
        required: true
      AWS_ROLE_ARN:
        required: true
  push:
    paths:
      - "app/admin/**"
      - "app/api/**"
      - "lib/**"
      - "infra/**"
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test -- --runInBand

  build-and-push:
    runs-on: ubuntu-latest
    needs: lint-test
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/platform-gateway:${{ inputs.image_tag || github.sha }} -f docker/platform-gateway.Dockerfile .
      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}/platform-gateway:${{ inputs.image_tag || github.sha }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Sync Argo application
        uses: imranismail/setup-argocd-cli@v2
      - name: Trigger rollout
        run: |
          argocd login $ARGO_SERVER --sso
          argocd app set platform-gateway --parameter image.tag=${{ inputs.image_tag || github.sha }}
          argocd app sync platform-gateway
